# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebToPayResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True)),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('flag', models.BooleanField(default=False)),
                ('flag_info', models.TextField(blank=True)),
                ('projectid', models.BigIntegerField(help_text=b'Unikalus projekto numeris. Tik patvirtinti projektai gali priimti \xc4\xafmokas', null=True)),
                ('orderid', models.CharField(help_text=b'U\xc5\xbesakymo numeris i\xc5\xa1 j\xc5\xabs\xc5\xb3 sistemos', max_length=40)),
                ('lang', models.CharField(blank=True, help_text=b'Galima nurodyti naudotojo kalb\xc4\x85, jeigu tokios kalbos mok\xc4\x97jimai.lt nepalaiko bus parinkta kalba pagal lankytojo IP adres\xc4\x85 arba angl\xc5\xb3 kalba pagal nutyl\xc4\x97jim\xc4\x85. (LIT, LAV, EST, RUS, ENG, GER, POL)', max_length=3)),
                ('amount', models.BigIntegerField(help_text=b'Suma centais, kuri\xc4\x85 klientas turi apmok\xc4\x97ti', null=True)),
                ('currency', models.CharField(help_text=b'Mok\xc4\x97jimo valiuta (LTL, USD, EUR), kuria pageidaujate, kad klientas mok\xc4\x97t\xc5\xb3. Jeigu nurodyta valiuta per pasirinkt\xc4\x85 mok\xc4\x97jimo b\xc5\xabd\xc4\x85 negali b\xc5\xabti priimta, sistema automati\xc5\xa1kai pagal dienos kurs\xc4\x85 konvertuos \xc4\xaf palaikom\xc4\x85 valiut\xc4\x85. Atsakyme \xc4\xaf J\xc5\xabs\xc5\xb3 svetain\xc4\x99 bus paduoti payamount ir paycurrency', max_length=3)),
                ('payment', models.CharField(help_text=b'Mok\xc4\x97jimo b\xc5\xabdas. Parametras, kuriame nieko nenurodoma (paliekamas tu\xc5\xa1\xc4\x8dias). Naudotojui bus pateikta lentel\xc4\x97 su mok\xc4\x97jimo b\xc5\xabd\xc5\xb3 s\xc4\x85ra\xc5\xa1u, pasirinkimui. Jis naudojamas tik tuo atveju, jeigu norima, kad mok\xc4\x97jimas b\xc5\xabt\xc5\xb3 atliktas tik per konkret\xc5\xb3 mok\xc4\x97jimo b\xc5\xabd\xc4\x85', max_length=20)),
                ('country', models.CharField(help_text=b'Mok\xc4\x97tojo \xc5\xa1alis (LT, EE, LV, GB, PL, DE). Nurod\xc5\xbeius \xc5\xa1al\xc4\xaf, mok\xc4\x97tojui i\xc5\xa1 karto pateikiami mok\xc4\x97jimo b\xc5\xabdai, galimi toje \xc5\xa1alyje. Jeigu \xc5\xa1alis nenurodoma, sistema pagal mok\xc4\x97tojo IP adres\xc4\x85 nustato jo \xc5\xa1al\xc4\xaf. Mok\xc4\x97tojui paliekama galimyb\xc4\x97 pasikeisti \xc5\xa1al\xc4\xaf', max_length=2)),
                ('paytext', models.TextField(help_text=b'Mok\xc4\x97jimo paskirtis, kuri matosi darant pavedim\xc4\x85.')),
                ('_ss2', models.CharField(blank=True, help_text=b'Parametras, kurio pagalba yra tikrinama, ar i\xc5\xa1 m\xc5\xabs\xc5\xb3 serverio gavote atsakym\xc4\x85. Tai auk\xc5\xa1\xc4\x8diausio patikimumo lygio tikrinimo b\xc5\xabdas. Atsisi\xc5\xb3skite skripto pavyzd\xc4\xaf', max_length=255)),
                ('_ss1', models.CharField(blank=True, help_text=b'Parametras, kurio pagalba yra tikrinama, ar i\xc5\xa1 m\xc5\xabs\xc5\xb3 serverio gavote atsakym\xc4\x85. Tai -- \xc5\xbeemesnio nei _ss2 patikimumo lygio tikrinimo b\xc5\xabdas. Atsisi\xc5\xb3skite pavyzd\xc4\xaf', max_length=64)),
                ('name', models.CharField(blank=True, help_text=b'Mok\xc4\x97tojo vardas, gautas i\xc5\xa1 mok\xc4\x97jimo sistemos. Siun\xc4\x8diamas tik jeigu mok\xc4\x97jimo sistema tok\xc4\xaf suteikia', max_length=255)),
                ('surename', models.CharField(blank=True, help_text=b'Mok\xc4\x97tojo pavard\xc4\x97, gauta i\xc5\xa1 mok\xc4\x97jimo sistemos. Siun\xc4\x8diamas tik jeigu mok\xc4\x97jimo sistema tok\xc4\xaf suteikia', max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'payment did not succeed'), (1, 'payment succeeded'), (2, 'payment accepted, but not yet processed')], default=0, help_text=b'Mok\xc4\x97jimo b\xc5\xabkl\xc4\x97: 0 - apmok\xc4\x97jimas ne\xc4\xafvyko, 1 - apmok\xc4\x97ta s\xc4\x97kmingai, 2 - mok\xc4\x97jimo nurodymas priimtas, bet dar ne\xc4\xafvykdytas')),
                ('error', models.CharField(blank=True, help_text=b'Klaidos kodas', max_length=20)),
                ('test', models.SmallIntegerField(choices=[(0, b'Production'), (1, b'Test')], help_text=b'Parametras, kuriam esant galima testuoti sujungim\xc4\x85, tokiu b\xc5\xabdu apmok\xc4\x97jimas nevykdomas ir rezultatas gr\xc4\x85\xc5\xbeinamas i\xc5\xa1 karto, tartum b\xc5\xabt\xc5\xb3 sumok\xc4\x97ta. Norint testuoti, b\xc5\xabtina aktyvuoti testavimo re\xc5\xbeim\xc4\x85 prie konkretaus projekto, kai prisijungiate: "Paslaug\xc5\xb3 valdymas" -> "\xc4\xafmok\xc5\xb3 surinkimas" (prie konkretaus projekto) -> "Leisti testinius mok\xc4\x97jimus" (pa\xc5\xbeym\xc4\x97kite)', null=True)),
                ('p_email', models.TextField(help_text=b'Pirk\xc4\x97jo el. pa\xc5\xa1tas privalomas. Jeigu adresas nebus gautas, kliento bus pra\xc5\xa1oma j\xc4\xaf \xc4\xafvesti. \xc5\xa0iuo adresu mok\xc4\x97jimai.lt sistema informuos mok\xc4\x97toj\xc4\x85 apie apmok\xc4\x97jimo b\xc5\xabkl\xc4\x99')),
                ('requestid', models.CharField(blank=True, help_text=b'Tai u\xc5\xbeklausos numeris, kur\xc4\xaf gauname, kai \xc5\xbemogus nuspaud\xc5\xbeia ant banko ir kur\xc4\xaf pateikiame \xc4\xaf "callbackurl" laukelyje nurodyt\xc4\x85 nuorod\xc4\x85', max_length=40)),
                ('payamount', models.IntegerField(help_text=b'Suma centais, kuri\xc4\x85 perved\xc4\x97. Gali skirtis jeigu buvokonvertuota \xc4\xaf kit\xc4\x85 valiut\xc4\x85', null=True)),
                ('paycurrency', models.CharField(help_text=b'Mok\xc4\x97jimo valiuta (LTL, USD, EUR), kuri\xc4\x85 perved\xc4\x97. Gali skirtis nuo tos kurios pra\xc5\xa1\xc4\x97te, jeigu pasirinktas mok\xc4\x97jimo b\xc5\xabdas negal\xc4\x97jo priimti pra\xc5\xa1omos valiutos', max_length=10)),
                ('version', models.CharField(help_text=b'Mok\xc4\x97jimai.lt mok\xc4\x97jim\xc5\xb3 sistemos specifikacijos (API) versijos numeris', max_length=9)),
            ],
        ),
    ]
